spring:
  output.ansi.enabled: DETECT
  data:
    mongodb:
      database: 'groogagle'
      authentication-database: 'groogagle'
      username: 'groogagle'
      password: 'gr00gagle1'
      host: '127.0.0.1'
      port: 27017
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy

logging:
  level.root: INFO
  file:
    path: 'logs'
    name: '${logging.file.path}/groogagle.log'

discord:
  token: 'OTcxODAwMDg4MDg1MTY0MDgy.YnPxXA.Uu-xZ9c50kE5yWbsedqMSQAzRQU'
  default-prefix: '>'
  developer-mode: true
  developer-guild: '971858225538404452'
  status-messages:
    - Playing Asphalt 9
    - Watching your races
    - Watching you
    - Watching feuerrm's videos
    - Listening to feuerrm's music
    - Listening to you
  # Real PT:
#  pt-guild: '288044166070665216'
#  pt-quiz-logs: '600674612593950720'
#  pt-join-logs: '288047167128600576'
#  pt-welcome-channel: '571684297568944131'
#  pt-driver-role: '361315396739006465'
#  pt-question-role: '570829494529818624'
  # Dev Server PT:
  pt-guild: '971858225538404452'
  pt-quiz-logs: '972152599119798272'
  pt-join-logs: '972149042194837584'
  pt-welcome-channel: '972149431954702356'
  pt-driver-role: '972149070351200267'
  pt-question-role: '972149116773736478'

version-control:
  repository: 'groogagle-jda'
  owner: 'garageagleMC'
  provider: 'github.com'